### ISSUE TITLE
Respect the order of selection.members

### ISSUE THREAD

**Issue by hSaria** [mkdocstrings/mkdocstrings#102]
**Is your feature request related to a problem? Please describe.**
Respect the order of `selection.members` when displaying the attributes/methods of a class.

**Describe the solution you'd like**
Ordering the sections of a class according to how they were listed under `selection.members`.

**Describe alternatives you've considered**
A new option can be introduced that deals specifically with sorting, but I feel that introduces one more thing to maintain.

Another option would be to sort the methods in the same order as they were defined in the class, though I can see this becoming an issue for folks that want to sort their methods in the code in one way and their docs in another. 

**Additional context**
Assuming there is a class with the methods `add`, `subtract`, `multiply`, and `divide`, the docs currently list them in alphabetical order.

I would like to manually specify an order, maybe something like so:
```
::: module.Class
    selection:
      members:
        - add
        - subtract
        - multiply
        - divide
```

**Comment by pawamoy** [comment]
I think it would be fair to respect the specified members order, though I'd like to have the opinion of others using this feature :slightly_smiling_face:  @ofek @florimondmanca @StephenBrown2 @chrieke (from #44)

Additionally, a `sorting` option would be nice. Sphinx has that: source order, alphabetical order, and group order IIRC?

**Comment by ofek** [comment]
Yes please! The natural order of `members` should be the default.

**Comment by StephenBrown2** [comment]
Just a note, Sphinx sorts the members by default. TIL that that's configurable!

**Comment by ofek** [comment]
I'll take any way we choose 🙂

**Comment by pawamoy** [comment]
Let's do this then. Just opened https://github.com/pawamoy/pytkdocs/issues/29

**Comment by ofek** [comment]
@pawamoy Hmm, I see your preferred solution in https://github.com/mkdocstrings/pytkdocs/issues/29 but wouldn't it make more sense to have the renderer read the members and act accordingly? Especially since the renderer has since added a new sorting option https://github.com/mkdocstrings/mkdocstrings/pull/274

**Comment by pawamoy** [comment]
See my answer here: https://github.com/mkdocstrings/pytkdocs/issues/29#issuecomment-993833625

**Comment by pawamoy** [comment]
Fixed in the new handler (not the legacy one, though it's possible to fix now).

**Comment by samuelcolvin** [comment]
This is marked as closed, but as far as I can tell, the original request (which is what I need) to respect the order of `members` is still not supported - the only options are `alphabetical` and `source` - as per [here](https://mkdocstrings.github.io/python/usage/configuration/members/?h=sort#with-inherited-members).

Is there any possibility to re-open this and provide a way to respect the order from `member`?

**Comment by pawamoy** [comment]
The `members_order` option is ignored when a list of members is specified, however the `group_by_category` one still comes into play (and it is on by default). Maybe try to set it to false to see if the order is better? We can consider ignoring this option as well when members are specified.
