### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: alias.html

### ISSUE THREAD

**Issue by joaompinto** [mkdocstrings/mkdocstrings#451]
**Describe the bug**

While running mkdocs build I get an exception:
```sh
$ mkdocs build
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: C:\Users\lameg\kubekind\site
WARNING  -  mkdocstrings_handlers: 1 aliases were still unresolved after 2 iterations
ERROR    -  mkdocstrings: Template 'alias.html' not found for 'python' handler and theme 'material'.
ERROR    -  Error reading page 'index.md': alias.html
Traceback (most recent call last):
  File "C:\Users\lameg\miniforge3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\lameg\miniforge3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lameg\miniforge3\Scripts\mkdocs.exe\__main__.py", line 7, in <module>
  File "C:\Users\lameg\miniforge3\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\lameg\miniforge3\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\lameg\miniforge3\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\lameg\miniforge3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\lameg\miniforge3\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\lameg\miniforge3\lib\site-packages\mkdocs\__main__.py", line 192, in build_command
    build.build(config.load_config(**kwargs), dirty=not clean)
  File "C:\Users\lameg\miniforge3\lib\site-packages\mkdocs\commands\build.py", line 292, in build
    _populate_page(file.page, config, files, dirty)
  File "C:\Users\lameg\miniforge3\lib\site-packages\mkdocs\commands\build.py", line 174, in _populate_page
    page.render(config, files)
  File "C:\Users\lameg\miniforge3\lib\site-packages\mkdocs\structure\pages.py", line 175, in render
    self.content = md.convert(self.markdown)
  File "C:\Users\lameg\miniforge3\lib\site-packages\markdown\core.py", line 264, in convert
    root = self.parser.parseDocument(self.lines).getroot()
  File "C:\Users\lameg\miniforge3\lib\site-packages\markdown\blockparser.py", line 90, in parseDocument
    self.parseChunk(self.root, '\n'.join(lines))
  File "C:\Users\lameg\miniforge3\lib\site-packages\markdown\blockparser.py", line 105, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
  File "C:\Users\lameg\miniforge3\lib\site-packages\markdown\blockparser.py", line 123, in parseBlocks
    if processor.run(parent, blocks) is not False:
  File "C:\Users\lameg\miniforge3\lib\site-packages\mkdocstrings\extension.py", line 121, in run
    html, handler, data = self._process_block(identifier, block, heading_level)
  File "C:\Users\lameg\miniforge3\lib\site-packages\mkdocstrings\extension.py", line 209, in _process_block
    rendered = handler.render(data, options)
  File "C:\Users\lameg\miniforge3\lib\site-packages\mkdocstrings_handlers\python\handler.py", line 215, in render
    template = self.env.get_template(f"{data.kind.value}.html")
  File "C:\Users\lameg\miniforge3\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Users\lameg\miniforge3\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\lameg\miniforge3\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\lameg\miniforge3\lib\site-packages\jinja2\loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: alias.html
```

**To Reproduce**

```sh
git clone git@github.com:joaompinto/kubekind.git
cd kubekind
pip install mkdocs mkdocstrings mkdocstrings[python]
mkdocs build
```

**Expected behavior**

**Information (please complete the following information):**
- OS:  Windows 10
- mkdocstrings 0.19.0

**Comment by motey** [comment]
Same error here, any new ideas?

**Comment by motey** [comment]
Ok, could work around this error by NOT using indirect imports (hope this is the correct term)

Lets have an example

``` 
/myProj
-__init__.py
    -/main
        -__init__.py
        -main.py
    -/sub1
        -__init__.py
        -sub1.py <-- "sub1Class" in here
```

content of `/myProj/main/__init__.py`

```
from myProj.sub1.sub1 import sub1Class
``` 

and in the mkdoc md file i referenced the class as

```
::: myProj.main.sub1Class
    :docstring:
    :members:
```
which provoked the error.

when changin the class reference to

```
::: myProj.sub1.sub1.sub1Class
    :docstring:
    :members:
```

the error was gone

**Comment by pawamoy** [comment]
Sorry for the delay and thank you for the workaround. I'll eventually get to this as it's clearly a bug.

**Comment by motey** [comment]
Thanks a lot. i'll try to find some time the next days to setup a simplified project-repo to reproduce the error.

**Comment by motey** [comment]
Ok, looks like my claim was wrong. I could NOT reproduce the error via indirect imports. 

https://github.com/motey/mkdocstrings-451

**Comment by HacKanCuBa** [comment]
hmmm still happening, I arrived here after checking out #404, no solution for now :(

**Comment by pawamoy** [comment]
The original issue reported by @joaompinto  seems to happen because `__init__.py` modules are missing from both `resources` and `storage`. The underlying tool, [Griffe](https://github.com/mkdocstrings/griffe), considers it an error and skips the modules in these folders (Griffe does not accept namespace packages inside of regular packages).

This is shown by the logs:

```console
% griffe dump kubekind -o/dev/null -LDEBUG
INFO       Loading package kubekind
DEBUG      Found kubekind: loading
DEBUG      Loading path kubekind/__init__.py
DEBUG      Loading path kubekind/kind.py
DEBUG      Loading path kubekind/__main__.py
DEBUG      Skip kubekind/resources/container.py, it is not importable. Missing __init__ module?
DEBUG      Skip kubekind/resources/pod.py, it is not importable. Missing __init__ module?
DEBUG      Skip kubekind/storage/volumemount.py, it is not importable. Missing __init__ module?
DEBUG      Skip kubekind/storage/emptydir.py, it is not importable. Missing __init__ module?
INFO       Finished loading packages
```

So the easy solution is to add the missing `__init__.py` modules.

@motey @HacKanCuBa can you confirm the issue is caused by missing `__init__.py` modules as well on your side?
If not, could you provide a public repository from which I can replicate the issue? Thanks.

**Comment by HacKanCuBa** [comment]
> ```
> mkdocs build -v
> ```

Hmmm interesting, I do not see that `griffe` issue in my log:
```
...
INFO     -  Cleaning site directory
INFO     -  Building documentation to directory: /home/hackan/Workspace/blake2signer/docs/site
DEBUG    -  An external link to 'https://blake2signer.hackan.net/en/stable/' is included in the
            'nav' configuration.
DEBUG    -  An external link to 'https://blake2signer.hackan.net/en/latest/' is included in the
            'nav' configuration.
DEBUG    -  An external link to 'https://readthedocs.org/projects/blake2signer/' is included in
            the 'nav' configuration.
DEBUG    -  Reading markdown pages.
DEBUG    -  Reading: index.md
DEBUG    -  Running 1 `page_markdown` events
DEBUG    -  Running 1 `page_content` events
DEBUG    -  Reading: bases.md
DEBUG    -  Running 1 `page_markdown` events
DEBUG    -  mkdocstrings: Matched '::: blake2signer.bases.Base'
DEBUG    -  mkdocstrings: Using handler 'python'
DEBUG    -  mkdocstrings: Collecting data
DEBUG    -  griffe: Found blake2signer: loading
DEBUG    -  griffe: Loading path /home/hackan/Workspace/blake2signer/blake2signer/__init__.py
DEBUG    -  griffe: Loading path /home/hackan/Workspace/blake2signer/blake2signer/signers.py
DEBUG    -  griffe: Loading path /home/hackan/Workspace/blake2signer/blake2signer/utils.py
DEBUG    -  griffe: Loading path /home/hackan/Workspace/blake2signer/blake2signer/interfaces.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/compressors.py
DEBUG    -  griffe: Loading path /home/hackan/Workspace/blake2signer/blake2signer/errors.py
DEBUG    -  griffe: Loading path /home/hackan/Workspace/blake2signer/blake2signer/encoders.py
DEBUG    -  griffe: Loading path /home/hackan/Workspace/blake2signer/blake2signer/bases.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/serializers.py
DEBUG    -  griffe: Loading path /home/hackan/Workspace/blake2signer/blake2signer/mixins.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/hashers/__init__.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/tests/__init__.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/hashers/blake3_package.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/hashers/blakehashers.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/tests/test_hashers.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/tests/test_signer.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/tests/test_serializersigner.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/tests/test_timestampsigner.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/tests/test_utils.py
DEBUG    -  griffe: Loading path
            /home/hackan/Workspace/blake2signer/blake2signer/tests/bases.py
DEBUG    -  griffe: Alias blake2signer.Blake2SerializerSigner was resolved to
            blake2signer.signers.Blake2SerializerSigner
DEBUG    -  griffe: Alias blake2signer.Blake2Signature was resolved to
            blake2signer.signers.Blake2Signature
DEBUG    -  griffe: Alias blake2signer.Blake2SignatureDump was resolved to
            blake2signer.signers.Blake2SignatureDump
DEBUG    -  griffe: Alias blake2signer.Blake2Signer was resolved to
            blake2signer.signers.Blake2Signer
DEBUG    -  griffe: Alias blake2signer.Blake2TimestampSigner was resolved to
            blake2signer.signers.Blake2TimestampSigner
DEBUG    -  griffe: Alias resolution error for blake2signer.hashers.blake3 -> blake3.blake3
DEBUG    -  griffe: Alias blake2signer.hashers.has_blake3 was resolved to
            blake2signer.hashers.blake3_package.has_blake3
DEBUG    -  griffe: Alias blake2signer.hashers.BLAKE2Hasher was resolved to
            blake2signer.hashers.blakehashers.BLAKE2Hasher
DEBUG    -  griffe: Alias blake2signer.hashers.BLAKE3Hasher was resolved to
            blake2signer.hashers.blakehashers.BLAKE3Hasher
DEBUG    -  griffe: Alias blake2signer.hashers.HasherChoice was resolved to
            blake2signer.hashers.blakehashers.HasherChoice
DEBUG    -  griffe: Iteration 1 finished, 9 aliases resolved, still 1 to go
DEBUG    -  griffe: Alias resolution error for blake2signer.hashers.blake3 -> blake3.blake3
DEBUG    -  griffe: Iteration 2 finished, 0 aliases resolved, still 1 to go
WARNING  -  mkdocstrings_handlers: 1 aliases were still unresolved after 2 iterations
DEBUG    -  mkdocstrings: Updating renderer's env
DEBUG    -  mkdocstrings: Rendering templates
...
```

This is from my open-source project, you can build the docs yourself if needed: https://gitlab.com/hackancuba/blake2signer/

1. Clone the repo: `git clone git@gitlab.com:hackancuba/blake2signer.git`
2. Go into project dir, ignore main project: `cd blake2signer`
3. Go into docs subdir: `cd docs`
4. Install deps: `poetry install` (a `.venv` dir is automatically created locally by Poetry)
5. Run mkdocs: `poetry run mkdocs build -v`

**Comment by pawamoy** [comment]
Can you try again with Griffe installed from master branch? `poetry run pip install git+https://github.com/mkdocstrings/griffe`

I've fixed several things, did not get the chance to release yet.

**Comment by HacKanCuBa** [comment]
> Can you try again with Griffe installed from master branch? `poetry run pip install git+https://github.com/mkdocstrings/griffe`
> 
> I've fixed several things, did not get the chance to release yet.

Interestingly, the log changed a bit, but yet it still throws the warning (or the error when I force it to reference directly the offending file).

**Comment by pawamoy** [comment]
So, what's the issue? You don't want the `X aliases were still unresolved after N iterations` message to be logged as a warning? We can turn it to a DEBUG one :slightly_smiling_face:

**Comment by HacKanCuBa** [comment]
haha no, that's not the issue. if i want to show docs for the object in question, it crashes instead of giving a warning (see the second part of [my prev comment](https://github.com/mkdocstrings/mkdocstrings/issues/451#issuecomment-1338552517))

**Comment by pawamoy** [comment]
I see, thanks for the explanation! (I'll still change the warning to a debug statement)

So, Griffe does not try to load external packages when resolving aliases. If you want to force it to load `blake3`, so that you are able to document its objects directly or through aliases (objects from blake3 imported in your own code), you'll have to add at least one autodoc instruction beginning with blake3, for example:

```ms
::: blake3.some.small.object
    options:
      shot_root_toc_entry: false

<!-- you can then hide it with something like
<style>.doc-object:has(> #blake3.some.small.object) {display: none;}</style>
-->
```

I'm planning on adding a configuration option to tell Griffe to (pre)load additional modules without having to resort to that workaround :slightly_smiling_face:

**Comment by HacKanCuBa** [comment]
yes, thanks!
BTW, I think a warning is perfectly fine there, I would certainly leave it as it is, because it is indicating an actual issue :)

**Comment by pawamoy** [comment]
Yeah you're right, I don't understand right now why the warning is not more often displayed though. Anyway, bad news: blake3 (which is compiled) is lying about the parent module of `blake3.blake3.blake3`: it says it's `builtins`. Not sure what hackery they actually do :confused: I guess I'll have to special case it in Griffe, but that doesn't make me so happy :joy:

**Comment by HacKanCuBa** [comment]
> Yeah you're right, I don't understand right now why the warning is not more often displayed though. Anyway, bad news: blake3 (which is compiled) is lying about the parent module of `blake3.blake3.blake3`: it says it's `builtins`. Not sure what hackery they actually do 😕 I guess I'll have to special case it in Griffe, but that doesn't make me so happy 😂

hahaha damn. hmmm, well, the Zen says that no special case is special enough :P
I could manually add some docs, and be done w/ it :)

**Comment by HacKanCuBa** [comment]
BTW, thanks so much for this!

**Comment by pawamoy** [comment]
You're welcome! You can also open a new issue with just the link to [this comment](https://github.com/mkdocstrings/mkdocstrings/issues/451#issuecomment-1353709610), this way I don't forget about it :slightly_smiling_face:

**Comment by HacKanCuBa** [comment]
I have bad news: I did a quick test w/ latest `blake3` and `griffe@master`, and this is still happening.
I'll keep digging, and open an issue directly in griffe. Thanks for everything!

**Comment by pawamoy** [comment]
Meh :confused: OK, thanks for reporting back, I'll continue to investigate as well.

**Comment by pawamoy** [comment]
I wonder if this is because @oconnor663 set the parent to module to `blake3` instead of `blake3.blake3` :thinking:

**Comment by pawamoy** [comment]
Or we simply hit the design flaw where modules and members of the same cannot coexist, while this is possible in Python itself.

**Comment by pawamoy** [comment]
Well, it's the former. If we patch the module of the `blake3` class to be `blake3.blake3` instead of `blake3`, it's correctly inspected instead of being marked as an alias to `blake3.blake3`.

If we don't, Griffe thinks that `blake3.blake3.blake3` is an alias to `blake3.blake3`, the alias is correctly resolved, but then this module does not have the members of the class (obviously), resulting in a collection error.

**Comment by pawamoy** [comment]
If `blake3` patches the module (again :pray: :bow: :heart:), then you can enable the `md_in_html` Markdown extension in `mkdocs.yml` and use this:

```markdown
<div style="display: none;" markdown=1>

::: blake3
    options:
        members: false
        show_root_heading: false
        show_root_toc_entry: false

</div>

::: blake2signer.hashers
```

**Comment by oconnor663** [comment]
I'm pretty new to the behavior of `__module__`, so it's certainly possible I did the wrong thing here. But intuitively it seems correct that the module should be `blake3`. That's consistent with the following toy example:

`blake3.py`
```py
class blake3:
    pass
```

`main.py`
```py
from blake3 import blake3
print(repr(blake3.__module__))
```

```
$ python3 main.py
'blake3'
```

I don't think anyone expects `main.py` to print `blake3.blake3`, but then I'm confused reading the thread above. What am I missing?

**Comment by oconnor663** [comment]
See also the pure-C port, which uses Python's C API directly. There we set [`.tp_name = "blake3.blake3"`](https://github.com/oconnor663/blake3-py/blob/52ae7c52d14d237a019baf14134baec0970b629b/c_impl/blake3module.c#L299), and Python [infers based on the dots](https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_name) that `__module__` should be `"blake3"`.

**Comment by pawamoy** [comment]
Your toy example is correct, however your code/project has one more layer:

```bash
blake3/  # <- module == blake3
    __init__.py  # <- imports blake3 class from compiled blake3 below
    blake3.cpython-311-x86_64-linux-gnu.so  # <- module == blake3.blake3
```

Generally, it seems that objects do have the full, canonical path to the module they are defined in as value for `__module__`. Some examples:

```pycon
>>> from griffe import load_git  # indirect import
>>> load_git.__module__
'griffe.git'

>>> from griffe.agents.base import BaseVisitor  # direct import
>>> BaseVisitor.__module__
'griffe.agents.base'
```

**Comment by oconnor663** [comment]
Ah interesting. It looks like that's an [implementation detail of the Maturin build tool](https://www.maturin.rs/project_layout.html). I've opened a discussion question about best practices here: https://github.com/PyO3/maturin/discussions/1365. Please chime in if you have any thoughts about Maturin/PyO3, or if you can clarify exactly how the `mkdocs` tool is getting confused. (I'm not familiar with it.)

**Comment by oconnor663** [comment]
The Maturin maintainer has asked for repro steps here: https://github.com/PyO3/maturin/discussions/1365#discussioncomment-4454070. Could someone here add a `mkdocs` repro to that thread?

**Comment by oconnor663** [comment]
Just published `blake3` v0.3.3 with `__module__` set to `blake3.blake3`. Could you give this another try?

**Comment by pawamoy** [comment]
Seems to be working fine! I'll let @HacKanCuBa confirm :slightly_smiling_face:

**Comment by HacKanCuBa** [comment]
> `md_in_html`

Indeed, it does work when I do something like explained here :D 🥳 

It still fails if I use `::: blake2signer.hashers.blake3` instead of `::: blake3`, but this is good enough 😅

**Comment by pawamoy** [comment]
As I tried to explain before, `::: blake2signer.hashers.blake3` will not make Griffe load the `blake3` package, so you won't have any information about the `blake3` class.

The idea is that later, you'll be able to use something like this:

```yaml
# mkdocs.yml
plugins:
- mkdocstrings:
    handlers:
      python:
        preload: [blake3]
```

...so that you don't have to rely on this hidden div hack :slightly_smiling_face:
